<h1>Login Administrador</h1>
<p><a href="<?= BASE_URL ?>/" style="text-decoration:none;">← Volver al Inicio</a></p>
<?php if (!empty($error)): ?>
<p style="color:red"><?= $error ?></p>
<?php endif; ?>
<form method="POST" action="<?= BASE_URL ?>/admin/login">
    <label>Usuario:</label><br>
    <input type="text" name="usuario" required><br>
    <label>Contraseña:</label><br>
    <input type="password" name="password" required><br><br>
        <button type="submit">Ingresar</button>
</form>