<?php
// La sesión ya se inicia en index.php
$nombreAdmin = (isset($_SESSION['admin']['nombre'])) ? $_SESSION['admin']['nombre'] : 'Invitado';
?>

<h1>Panel de Administración</h1>
<p>Bienvenido, <?= htmlspecialchars($nombreAdmin) ?></p>
<p><a href="<?= BASE_URL ?>/" style="text-decoration:none;">← Ir al Inicio Público</a></p>
<ul>
    <li><a href="<?= BASE_URL ?>/admin/habitaciones">Administrar Habitaciones</a></li>
    <li><a href="<?= BASE_URL ?>/admin/tipos">Administrar Tipos de Habitación</a></li>
    <li><a href="<?= BASE_URL ?>/admin/logout">Cerrar sesión</a></li>
</ul>




</ul>



